server:
  port: 8088
  servlet:
    context-path: /api
spring:
  application:
    name: CloudPicture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CloudPicture
    username: root
    password: 58855727@Un228
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除实体字段
      logic-delete-value: 1  # 逻辑已删除值 默认1
      logic-not-delete-value: 0 # 逻辑未删除值 默认0